### ISSUE TITLE
On running dev getting error :  of prisma client genration scripts are missing

### ISSUE THREAD

**Issue by abhayymishraa** [code100x/chess#111]
# Prisma client error 

On running dev command prisma client is not generating automatically 

***Expected Behaviour*** 

On running run dev command after  installing package it should run the primsa client script it run if we go  to packages and then genrate basically genrate scripts arre missing in turbo.json

[Screenshot from 2024-04-20 14-15-20](https://github.com/code100x/chess/assets/133818254/18c3b7d0-16e9-4391-98d8-8443e425a606)

**Comment by vishalmishraa** [comment]
go into 
``` 
cd packages/db
```

then install 

```
yarn add @prisma/client@5.12.1 prisma@5.12.0

```

**Comment by abhayymishraa** [comment]
haha i created them issue forr myself it waas the first time for me to contributing a repo

**Comment by skushagra9** [comment]
i guess, we need to make a postinstall script
