### ISSUE TITLE
Add "start" script to package.json in apps/frontend directory

### ISSUE THREAD

**Issue by KelvinPuyam** [code100x/chess#170]
The package.json file in the apps/frontend directory is missing a "start" script, which is required to start the development server using npm start. This issue is to add the "start" script to the package.json file in the apps/frontend directory.

![Screenshot 2024-04-21 185844](https://github.com/code100x/chess/assets/112263229/7957c72b-ae3f-4171-bab7-d012996cd0fa)

**Comment by Sama-004** [comment]
> The package.json file in the apps/frontend directory is missing a "start" script, which is required to start the development server using npm start. This issue is to add the "start" script to the package.json file in the apps/frontend directory.

just use npm run dev

**Comment by KelvinPuyam** [comment]
Yh that should do but I dont get the localhost url when I run that.
I get an output like:
> dev
> turbo dev

• Packages in scope: @repo/db, @repo/eslint-config, @repo/store, @repo/tailwind-config, @repo/typescript-config, @repo/ui, backend, backend1, chessnative, frontend
• Running dev in 10 packages
• Remote caching disabled
@repo/db:db:generate: cache bypass, force executing cfefa2929b91ad51
@repo/db:dev: cache bypass, force executing 42102e3c7bf88af2
frontend:dev: cache bypass, force executing 9e95a513a97d9ce7

 Tasks:    0 successful, 3 total
Cached:    0 cached, 3 total
  Time:    1.762s

**Comment by KelvinPuyam** [comment]
Ohh right it worked. Thanks man.
