### ISSUE TITLE
Timer issues after game end

### ISSUE THREAD

**Issue by pasagadisriram** [code100x/chess#240]
1. Once a player wins I see undefined ws message ( I didn't have screenshot now)
2. If opponent ignores logged in player need to wait 10 mins and doesn't have any action buttons like Abort/Start new game
3. Timer doesn't stop after 10 mins. It runs for infinite even after 0:00 

![image](https://github.com/code100x/chess/assets/8892411/5ab252ac-862d-4a2f-8774-9f8483970aee)

Page shows connecting message if we switch between browser tabs

**Comment by Airbornharsh** [comment]
Yeah I got it
I have a PR #198
after merged i can work on this

as there may be many conflicts

**Comment by pasagadisriram** [comment]
Issue resolved in https://github.com/code100x/chess/pull/269
