### ISSUE TITLE
Add a quit button in game

### ISSUE THREAD

**Issue by amanasati01** [code100x/chess#244]
I have already solved this issue
![Screenshot from 2024-04-25 13-41-54](https://github.com/code100x/chess/assets/117284887/4cf8fbd1-214b-4dcb-a4de-2669b9041006)
![Screenshot from 2024-04-25 13-42-07](https://github.com/code100x/chess/assets/117284887/b13692e0-f99f-4568-aa7a-84eefdccf276)

**Comment by Sama-004** [comment]
Instead of quit it should be resign as that is the term used for quitting in chess

**Comment by amanasati01** [comment]
yes i will change.

**Comment by nimit9** [comment]
Already done in #180

**Comment by amanasati01** [comment]
it is already done ?

**Comment by Airbornharsh** [comment]
Yeah

**Comment by Sama-004** [comment]
> it is already done ?

yeah done in #180. Please close this issue

**Comment by Sama-004** [comment]
@amanasati01 please close this issue
