### ISSUE TITLE
Shareable links

### ISSUE THREAD

**Issue by hkirat** [code100x/chess#294]
let a user create a game and share it with a friend to join in

**Comment by adi790uu** [comment]
@hkirat can you assign me?

**Comment by amanasati01** [comment]
i am working on this figureout how to do it

**Comment by adi790uu** [comment]
@amanasati01 do you want to collaborate

**Comment by hkirat** [comment]
multiple implementations are fine

**Comment by nischal-shetty2** [comment]
@hkirat i think there should also be a feature to give users an id and then send a request in-game to your friend's id

> multiple implementations are fine

**Comment by amanasati01** [comment]
@adi790uu yes let's collaborate

**Comment by adi790uu** [comment]
Okay @amanasati01
