### ISSUE TITLE
Adding Play Against a Computer Feature

### ISSUE THREAD

**Issue by crampussm** [code100x/chess#329]
As of now the play against a computer option does not work and it says coming soon
![Screenshot 2024-05-18 184017](https://github.com/code100x/chess/assets/82692857/f6117afb-4bda-47f9-bf08-6ae331cb7122)

The goal is to add the feature to play against a bot

**Comment by janareddyc7** [comment]
it has been already done , just waiting for pullreq to be added into repo

**Comment by vishalmishraa** [comment]
@crampussm there is already a pr #276
