### ISSUE TITLE
link  not working 

### ISSUE THREAD

**Issue by MdTanwer** [code100x/chess#364]
i just try to explore the web  of this repo "https://chess.100xdevs.com/" show error 
![Screenshot 2024-07-11 075742](https://github.com/code100x/chess/assets/122739350/25bc9364-84f2-41eb-abe0-acd2ffd47b0b)

**Comment by PetjaPaivarinta** [comment]
same

**Comment by swappy-2003** [comment]
maybe a server error from Harkirat side

**Comment by Sri1302** [comment]
same bro it is not working

**Comment by venkyok** [comment]
i think the domain hosting has expired

**Comment by Sri1302** [comment]
ok that might be reason right

**Comment by MdTanwer** [comment]
not working
